[package]
name = "tatuin"
version = "0.6.0"
edition = "2024"
description = "Task Aggregator TUI for N providers"
homepage = "https://github.com/panter-dsd/tatuin"
license-file = "LICENSE.txt"
readme = "README.md"
rust-version = "1.85.1"

[dependencies]
async-trait = "0.1.88"
chrono = "0.4.41"
clap = { version = "4.5.38", features = ["derive"] }
color-eyre = "0.6.4"
colored = "3.0.0"
config = "0.15.11"
crossterm = { version = "0.29.0", features = ["event-stream"] }
ratatui = "0.29.0"
regex = "1.11.1"
reqwest = { version = "0.12.15", features = ["json"] }
serde = "1.0.219"
time = { version = "0.3.41", features = ["parsing", "formatting"] }
tokio = { version = "1.45.0", features = ["full"] }
tokio-stream = "0.1.17"
toml = "0.8.22"
url = "2.5.4"
url-builder = "0.1.1"
urlencoding = "2.1.3"
xdg = "2.5.2"
