[graph]
targets = []
all-features = true
no-default-features = false

[output]
feature-depth = 1

[advisories]
unmaintained = 'workspace'

[licenses]
allow = [
  "MIT",
  "Unicode-3.0",
  "Apache-2.0",
  "ISC",
  "Zlib",
  "BSD-3-Clause",
  "MPL-2.0",
]
confidence-threshold = 0.8
exceptions = []

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
# github = [""]
# gitlab = [""]
# bitbucket = [""]
