# https://github.com/crate-ci/typos/blob/master/docs/reference.md

[files]
extend-exclude = ["attribution"]

[default.extend-identifiers]

[default.extend-words]

[default]
extend-ignore-identifiers-re = ["ratatui", "Ratatui"]
