name: Release CI
on:
  push:
    branches:
      - master
jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        compiler:
          - stable
          - beta
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.compiler }}
          override: true
      - name: Install cargo-deb (for Ubuntu)
        if: contains(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install -y debhelper dh-autoreconf
      - name: Build the project
        run: cargo build --release
      - name: Package for Linux (if on Ubuntu)
        if: contains(matrix.os, 'ubuntu')
        run: cargo package --no-crates-io
      - name: Package for macOS (if on Mac OS)
        if: contains(matrix.os, 'macos')
        uses: actions/upload-artifact@v4
        with:
          name: rust-mac
          path: target/x86_64-apple-darwin/release/tatuin
      - name: Create release on GitHub (Linux only)
        if: contains(matrix.os, 'ubuntu')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-name: v${{ github.event.repository.default_branch }}
          body: Release ${{ github.event.repository.default_branch }}
          draft: false
      - name: Upload artifact to release (Linux only)
        if: contains(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v4
        with:
          name: tatuin-linux-x64
          path: target/x86_64-unknown-linux-gnu/release/tatuin
